- name: Install Droid Sans Mono Nerd Font Complete
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf
    dest: ~/Library/Fonts/Droid Sans Mono Nerd Font Complete.otf

- name: Install Droid Sans Mono Nerd Font Complete Mono
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.otf
    dest: ~/Library/Fonts/Droid Sans Mono Nerd Font Complete Mono.otf

- name: iTerm custom settings file
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "{{ ansible_env.PWD }}/roles/macOS/files"
