- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
  become: true

- name: Add ourselves to the docker group
  user:
    name: "{{ ansible_user }}"
    group: docker
  become: true
