- name: Add apt repositories
  command: add-apt-repository {{ item }}
  loop: "{{ apt_repositories }}"

- name: Update apt
  apt:
    update_cache: yes
  become: true

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ apt_packages }}"
  become: true

- name: apt cleanup
  apt:
    autoremove: true
  become: true

- name: Install Snap packages
  snap:
    name: "{{ item }}"
    state: latest
  loop: "{{ snap_packages }}"
  become: true
