- name: Create font directory
  file:
    path: ~/.local/share/fonts
    state: directory

- name: Install Droid Sans Mono Nerd Font Complete
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf
    dest: ~/.local/share/fonts/Droid Sans Mono Nerd Font Complete.otf

- name: Install Droid Sans Mono Nerd Font Complete Mono
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.otf
    dest: ~/.local/share/fonts/Droid Sans Mono Nerd Font Complete Mono.otf
